package com.lifebalance.finance.domain;

public enum FinanceHistoryActionType {
    ACCOUNT_CREATED,
    ACCOUNT_UPDATED,
    ACCOUNT_ARCHIVED,
    CATEGORY_CREATED,
    CATEGORY_UPDATED,
    CATEGORY_ARCHIVED,
    TRANSACTION_CREATED,
    TRANSACTION_UPDATED,
    TRANSACTION_VOIDED,
    BUDGET_CREATED,
    BUDGET_UPDATED,
    BUDGET_ARCHIVED,
    RECURRING_TRANSACTION_CREATED,
    RECURRING_TRANSACTION_UPDATED,
    RECURRING_TRANSACTION_PAUSED,
    RECURRING_TRANSACTION_RESUMED,
    RECURRING_TRANSACTION_ENDED
}
