package com.lifebalance.ai.domain;

public enum AiHistoryActionType {
    CONVERSATION_CREATED,
    MESSAGE_RECORDED,
    ASSISTANT_RESPONDED,
    CONVERSATION_ARCHIVED,
    RECOMMENDATION_GENERATED,
    RECOMMENDATION_APPLIED,
    RECOMMENDATION_DISMISSED,
    INSIGHT_GENERATED,
    INSIGHT_ARCHIVED
}
