server:
  port: ${NOTIFICATION_SERVICE_PORT:8094}

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}

eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:notification-service}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE}

management:
  endpoint:
    health:
      show-details: never
