ALTER TABLE resourcecapital.capital_allocations
    ADD COLUMN spent_amount DECIMAL(19, 4) NOT NULL DEFAULT 0;

ALTER TABLE resourcecapital.capital_allocations
    ADD COLUMN status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE';

ALTER TABLE resourcecapital.capital_allocations
    DROP CONSTRAINT chk_capital_allocations_amount;

ALTER TABLE resourcecapital.capital_allocations
    ADD CONSTRAINT chk_capital_allocations_amount
        CHECK (allocated_amount >= 0);

ALTER TABLE resourcecapital.capital_allocations
    ADD CONSTRAINT chk_capital_allocations_spent_amount
        CHECK (spent_amount >= 0);

ALTER TABLE resourcecapital.capital_allocations
    ADD CONSTRAINT chk_capital_allocations_status
        CHECK (status IN ('ACTIVE', 'CLOSED', 'RELEASED'));

CREATE INDEX idx_capital_allocations_cycle_status
    ON resourcecapital.capital_allocations (capital_cycle_id, status);

CREATE INDEX idx_capital_allocations_status_kind
    ON resourcecapital.capital_allocations (status, capital_type);

CREATE TABLE resourcecapital.capital_reallocations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_allocation_id UUID NOT NULL,
    to_allocation_id UUID NOT NULL,
    amount DECIMAL(19, 4) NOT NULL,
    reason VARCHAR(1000),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_capital_reallocations_from_allocation
        FOREIGN KEY (from_allocation_id)
        REFERENCES resourcecapital.capital_allocations (id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_capital_reallocations_to_allocation
        FOREIGN KEY (to_allocation_id)
        REFERENCES resourcecapital.capital_allocations (id)
        ON DELETE RESTRICT,
    CONSTRAINT chk_capital_reallocations_amount
        CHECK (amount > 0),
    CONSTRAINT chk_capital_reallocations_distinct_allocations
        CHECK (from_allocation_id <> to_allocation_id)
);

CREATE INDEX idx_capital_reallocations_from
    ON resourcecapital.capital_reallocations (from_allocation_id, created_at DESC);

CREATE INDEX idx_capital_reallocations_to
    ON resourcecapital.capital_reallocations (to_allocation_id, created_at DESC);

CREATE TABLE resourcecapital.capital_releases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    allocation_id UUID NOT NULL,
    released_amount DECIMAL(19, 4) NOT NULL,
    reason VARCHAR(1000),
    released_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_capital_releases_allocation
        FOREIGN KEY (allocation_id)
        REFERENCES resourcecapital.capital_allocations (id)
        ON DELETE RESTRICT,
    CONSTRAINT chk_capital_releases_released_amount
        CHECK (released_amount > 0)
);

CREATE INDEX idx_capital_releases_allocation_released_at
    ON resourcecapital.capital_releases (allocation_id, released_at DESC);
