server:
  shutdown: graceful
  forward-headers-strategy: framework

spring:
  profiles:
    default: local

  application:
    name: gateway

  cloud:
    gateway:
      server:
        webmvc:
          routes:

            - id: identity-service
              uri: lb://LIFEBALANCE-APP
              predicates:
                - Path=/api/auth/**,/api/users/**,/api/roles/**

            - id: task-service
              uri: lb://LIFEBALANCE-APP
              predicates:
                - Path=/api/tasks/**,/api/task-groups/**

            - id: finance-service
              uri: lb://LIFEBALANCE-APP
              predicates:
                - Path=/api/finance/**,/api/budgets/**,/api/transactions/**

            - id: notification-service
              uri: lb://LIFEBALANCE-APP
              predicates:
                - Path=/api/notifications/**

            - id: ai-service
              uri: lb://LIFEBALANCE-APP
              predicates:
                - Path=/api/ai/**

management:
  endpoints:
    web:
      exposure:
        include: health,info

  endpoint:
    gateway:
      enabled: true

    health:
      probes:
        enabled: true

info:
  app:
    name: LifeBalance Gateway
    version: 1.0.0
    description: Enterprise API Gateway

logging:
  level:
    root: INFO
    org.springframework.security: INFO
    org.springframework.cloud.gateway: INFO
    org.springframework.web: INFO

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger - %msg%n"
