server:
  port: ${APP_PORT:8081}

eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:lifebalance-app}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90

  client:
    register-with-eureka: true
    fetch-registry: true

    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://discovery-server:8761/eureka}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

  endpoint:
    health:
      show-details: when_authorized
