package com.lifebalance.task.integration;

public enum TaskIntegrationAction {
    TASK_CREATED,
    TASK_UPDATED,
    TASK_PLANNED,
    TASK_SCHEDULED,
    TASK_RESCHEDULED,
    TASK_MOVED,
    TASK_TIMELINE_CANCELLED,
    TASK_PROGRESS_UPDATED,
    TASK_PAUSED,
    TASK_RESUMED,
    TASK_COMPLETED,
    TASK_CANCELLED,
    TASK_REOPENED,
    TASK_ARCHIVED,
    TASK_RESTORED,
    TASK_DELETED,
    TASK_DUPLICATED,
    TASK_REMINDER_CREATED,
    TASK_REMINDER_UPDATED,
    TASK_REMINDER_CANCELLED
}
