services:
  postgres:
    ports: !reset []

  keycloak:
    ports: !reset []
    command:
      - start
      - --health-enabled=true
      - --metrics-enabled=true
      - --import-realm
    environment:
      KC_HOSTNAME_STRICT: ${KEYCLOAK_HOSTNAME_STRICT:-true}
      KC_HTTP_ENABLED: ${KEYCLOAK_HTTP_ENABLED:-true}

  discovery-server:
    ports: !reset []
    environment:
      SPRING_PROFILES_ACTIVE: prod

  identity-service:
    ports: !reset []
    environment:
      SPRING_PROFILES_ACTIVE: prod

  task-service:
    ports: !reset []
    environment:
      SPRING_PROFILES_ACTIVE: prod

  timeline-service:
    ports: !reset []
    environment:
      SPRING_PROFILES_ACTIVE: prod

  resource-capital-service:
    ports: !reset []
    environment:
      SPRING_PROFILES_ACTIVE: prod

  finance-service:
    ports: !reset []
    environment:
      SPRING_PROFILES_ACTIVE: prod

  notification-service:
    ports: !reset []
    environment:
      SPRING_PROFILES_ACTIVE: prod

  analytics-service:
    ports: !reset []
    environment:
      SPRING_PROFILES_ACTIVE: prod

  ai-service:
    ports: !reset []
    environment:
      SPRING_PROFILES_ACTIVE: prod

  gateway:
    ports: !reset []
    environment:
      SPRING_PROFILES_ACTIVE: prod
