services:
  postgres:
    ports:
      - "${POSTGRES_HOST_PORT:-5432}:5432"

  keycloak:
    ports:
      - "${KEYCLOAK_HOST_PORT:-8082}:8080"
      - "${KEYCLOAK_MGMT_HOST_PORT:-9000}:9000"

  rabbitmq:
    profiles: []

  redis:
    profiles: []

  minio:
    profiles: []

  prometheus:
    profiles: []

  grafana:
    profiles: []
