services:
  postgres:
    ports: []

  keycloak:
    ports: []
    command:
      - start
      - --health-enabled=true
      - --metrics-enabled=true
      - --import-realm
    environment:
      KC_HOSTNAME_STRICT: ${KEYCLOAK_HOSTNAME_STRICT:-true}
      KC_HTTP_ENABLED: ${KEYCLOAK_HTTP_ENABLED:-true}

  discovery-server:
    ports: []

  identity-service:
    ports: []

  task-service:
    ports: []

  timeline-service:
    ports: []

  resource-capital-service:
    ports: []

  finance-service:
    ports: []

  notification-service:
    ports: []

  analytics-service:
    ports: []

  ai-service:
    ports: []
