server:
  port: ${TASK_SERVICE_PORT:8092}

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://keycloak:8080/realms/lifebalance}

eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:task-service}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://discovery-server:8761/eureka}

management:
  endpoint:
    health:
      show-details: when_authorized
