package com.lifebalance.notification.domain;

public enum NotificationHistoryActionType {
    NOTIFICATION_CREATED,
    NOTIFICATION_SKIPPED,
    NOTIFICATION_QUEUED,
    NOTIFICATION_SENT,
    NOTIFICATION_FAILED,
    NOTIFICATION_RETRIED,
    NOTIFICATION_READ,
    NOTIFICATION_UNREAD,
    NOTIFICATION_ARCHIVED,
    PREFERENCE_UPDATED,
    TEMPLATE_CREATED,
    TEMPLATE_UPDATED,
    TEMPLATE_ARCHIVED
}
