package com.lifebalance.finance.dto;

import com.lifebalance.finance.domain.FinanceIncomeSourceType;
import com.lifebalance.finance.domain.FinanceTransactionStatus;
import com.lifebalance.finance.domain.FinanceTransactionType;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.UUID;

public record TransactionResponse(
        UUID id,
        UUID ownerId,
        FinanceTransactionType transactionType,
        FinanceTransactionStatus status,
        UUID sourceAccountId,
        String sourceAccountName,
        UUID destinationAccountId,
        String destinationAccountName,
        UUID categoryId,
        String categoryName,
        BigDecimal amount,
        String currencyCode,
        OffsetDateTime transactionDate,
        String transactionName,
        String description,
        UUID taskId,
        UUID capitalCycleId,
        UUID capitalAllocationId,
        OffsetDateTime voidedAt,
        String voidReason,
        UUID createdBy,
        UUID updatedBy,
        OffsetDateTime createdAt,
        OffsetDateTime updatedAt,
        FinanceIncomeSourceType incomeSourceType,
        String salaryPeriod,
        BigDecimal baseSalary,
        BigDecimal bonusAmount,
        BigDecimal deductionAmount,
        boolean systemGenerated
) {

    public TransactionResponse(
            UUID id,
            UUID ownerId,
            FinanceTransactionType transactionType,
            FinanceTransactionStatus status,
            UUID sourceAccountId,
            String sourceAccountName,
            UUID destinationAccountId,
            String destinationAccountName,
            UUID categoryId,
            String categoryName,
            BigDecimal amount,
            String currencyCode,
            OffsetDateTime transactionDate,
            String transactionName,
            String description,
            UUID taskId,
            UUID capitalCycleId,
            UUID capitalAllocationId,
            OffsetDateTime voidedAt,
            String voidReason,
            UUID createdBy,
            UUID updatedBy,
            OffsetDateTime createdAt,
            OffsetDateTime updatedAt,
            FinanceIncomeSourceType incomeSourceType,
            String salaryPeriod,
            BigDecimal baseSalary,
            BigDecimal bonusAmount,
            BigDecimal deductionAmount
    ) {
        this(
                id,
                ownerId,
                transactionType,
                status,
                sourceAccountId,
                sourceAccountName,
                destinationAccountId,
                destinationAccountName,
                categoryId,
                categoryName,
                amount,
                currencyCode,
                transactionDate,
                transactionName,
                description,
                taskId,
                capitalCycleId,
                capitalAllocationId,
                voidedAt,
                voidReason,
                createdBy,
                updatedBy,
                createdAt,
                updatedAt,
                incomeSourceType,
                salaryPeriod,
                baseSalary,
                bonusAmount,
                deductionAmount,
                false
        );
    }

    public TransactionResponse(
            UUID id,
            UUID ownerId,
            FinanceTransactionType transactionType,
            FinanceTransactionStatus status,
            UUID sourceAccountId,
            String sourceAccountName,
            UUID destinationAccountId,
            String destinationAccountName,
            UUID categoryId,
            String categoryName,
            BigDecimal amount,
            String currencyCode,
            OffsetDateTime transactionDate,
            String transactionName,
            String description,
            UUID taskId,
            UUID capitalCycleId,
            UUID capitalAllocationId,
            OffsetDateTime voidedAt,
            String voidReason,
            UUID createdBy,
            UUID updatedBy,
            OffsetDateTime createdAt,
            OffsetDateTime updatedAt
    ) {
        this(
                id,
                ownerId,
                transactionType,
                status,
                sourceAccountId,
                sourceAccountName,
                destinationAccountId,
                destinationAccountName,
                categoryId,
                categoryName,
                amount,
                currencyCode,
                transactionDate,
                transactionName,
                description,
                taskId,
                capitalCycleId,
                capitalAllocationId,
                voidedAt,
                voidReason,
                createdBy,
                updatedBy,
                createdAt,
                updatedAt,
                FinanceIncomeSourceType.ONE_OFF,
                null,
                null,
                null,
                null,
                false
        );
    }

    public TransactionResponse(
            UUID id,
            UUID ownerId,
            FinanceTransactionType transactionType,
            FinanceTransactionStatus status,
            UUID sourceAccountId,
            String sourceAccountName,
            UUID destinationAccountId,
            String destinationAccountName,
            UUID categoryId,
            String categoryName,
            BigDecimal amount,
            String currencyCode,
            OffsetDateTime transactionDate,
            String description,
            UUID taskId,
            UUID capitalCycleId,
            UUID capitalAllocationId,
            OffsetDateTime voidedAt,
            String voidReason,
            UUID createdBy,
            UUID updatedBy,
            OffsetDateTime createdAt,
            OffsetDateTime updatedAt
    ) {
        this(
                id,
                ownerId,
                transactionType,
                status,
                sourceAccountId,
                sourceAccountName,
                destinationAccountId,
                destinationAccountName,
                categoryId,
                categoryName,
                amount,
                currencyCode,
                transactionDate,
                null,
                description,
                taskId,
                capitalCycleId,
                capitalAllocationId,
                voidedAt,
                voidReason,
                createdBy,
                updatedBy,
                createdAt,
                updatedAt,
                FinanceIncomeSourceType.ONE_OFF,
                null,
                null,
                null,
                null,
                false
        );
    }
}
